#!/bin/bash
# ============================================================
# ReferPeople.in — Auto-create ALL backend .env files
# Run this ONCE on your EC2 server after cloning the repo
#
# Usage:
#   chmod +x create-env-files.sh
#   ./create-env-files.sh
# ============================================================

set -e

# ============================================================
# EDIT THESE VALUES BEFORE RUNNING
# ============================================================
DB_HOST="YOUR-RDS-ENDPOINT.ap-south-1.rds.amazonaws.com"
DB_PORT="5432"
DB_MASTER_PASSWORD="ReferPeople@DB2024!"

SERVER_IP="YOUR-EC2-PUBLIC-IP"
DOMAIN="referpeople.in"

# Generate a random secret key (or set your own 50-char string)
SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(50))" 2>/dev/null || \
             cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 50 | head -n 1)

AWS_ACCESS_KEY_ID="YOUR-AWS-ACCESS-KEY-ID"
AWS_SECRET_ACCESS_KEY="YOUR-AWS-SECRET-ACCESS-KEY"
AWS_S3_BUCKET="referpeople-media"
AWS_REGION="ap-south-1"

EMAIL_HOST_USER="your-email@gmail.com"
EMAIL_HOST_PASSWORD="your-gmail-app-password"

REDIS_URL="redis://redis:6379/0"
CORS_ORIGINS="http://${SERVER_IP},https://${DOMAIN},https://www.${DOMAIN}"

DEBUG="False"
# ============================================================

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

write_env() {
  local DIR="$1"
  local DB_NAME="$2"
  local DB_USER="$3"
  local DB_PASS="$4"

  cat > "${DIR}/.env" << EOF
# Auto-generated by create-env-files.sh
DEBUG=${DEBUG}
SECRET_KEY=${SECRET_KEY}
ALLOWED_HOSTS=${SERVER_IP},${DOMAIN},www.${DOMAIN},localhost,127.0.0.1

DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASS}

REDIS_URL=${REDIS_URL}
CELERY_BROKER_URL=redis://redis:6379/1

AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_S3_BUCKET=${AWS_S3_BUCKET}
AWS_REGION=${AWS_REGION}
AWS_S3_CUSTOM_DOMAIN=${AWS_S3_BUCKET}.s3.${AWS_REGION}.amazonaws.com

EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER=${EMAIL_HOST_USER}
EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
DEFAULT_FROM_EMAIL=noreply@${DOMAIN}

CORS_ALLOWED_ORIGINS=${CORS_ORIGINS}
CORS_ALLOW_ALL_ORIGINS=False

AXES_FAILURE_LIMIT=5
AXES_COOLOFF_TIME=1
EOF
  echo -e "${GREEN}Created${NC} ${DIR}/.env  (DB: ${DB_NAME})"
}

echo ""
echo -e "${BLUE}=====================================${NC}"
echo -e "${BLUE}  Creating .env files for all backends${NC}"
echo -e "${BLUE}=====================================${NC}"
echo ""

# Master Admin Backend
write_env "BRD_MasterAdmin_Backend_1.1" \
  "masteradmin_db" "masteradmin_user" "MasterAdminPass123!"

# Tenant / Auth Backend
write_env "BRD-MergedTenantMaster-Backend" \
  "tenant_db" "tenant_user" "TenantPass123!"

# CRM Backend
write_env "BRD_CRM_1.1_BACKEND" \
  "crm_db" "crm_user" "CrmPass123!"

# Finance Backend
write_env "BRD_FINANCE_DASHBOARD_Backend" \
  "finance_db" "finance_user" "FinancePass123!"

# Agents Backend
write_env "BRD-AgentsApp-Backend" \
  "agents_db" "agents_user" "AgentsPass123!"

# Channel Partner Backend
write_env "BRD-ChannelPartnerDashboard-Backend" \
  "channel_db" "channel_user" "ChannelPass123!"

# Fraud Team Backend
write_env "BRD-FraudTeam-Dashboard-Backend" \
  "fraud_db" "fraud_user" "FraudPass123!"

# Legal Dashboard Backend
write_env "BRD-LegalDashboard-Backend" \
  "legal_db" "legal_user" "LegalPass123!"

# Operations Backend
write_env "BRD-OperationVerification-Backend" \
  "operations_db" "operations_user" "OperationsPass123!"

# Sales CRM Backend
write_env "BRD-SalesCRM-Dashboard-Backend" \
  "salescrm_db" "salescrm_user" "SalesCrmPass123!"

# Tenant Admin Backend
write_env "BRD-TenantAdmin_backend_2.0" \
  "tenantadmin_db" "tenantadmin_user" "TenantAdminPass123!"

# Valuation Backend
write_env "BRD-Valuation-Dashboard-Backend" \
  "valuation_db" "valuation_user" "ValuationPass123!"

# Website Backend
write_env "BRD-website-main-backend" \
  "website_db" "website_user" "WebsitePass123!"

echo ""
echo -e "${GREEN}=====================================${NC}"
echo -e "${GREEN}  All .env files created!${NC}"
echo -e "${GREEN}=====================================${NC}"
echo ""
echo "Next steps:"
echo "  1. Review the .env files if needed"
echo "  2. Run: docker compose build"
echo "  3. Run: docker compose up -d"
echo ""
