# Generated by Django 4.2.7 on 2026-03-09 14:53
# Fixed: column may already exist; use IF NOT EXISTS to be idempotent

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_upload', '0001_initial'),
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database: only add the column if it doesn't already exist
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE data_ingestion_rawleadpool ADD COLUMN IF NOT EXISTS lead_id integer NOT NULL DEFAULT 1;",
                    reverse_sql="ALTER TABLE data_ingestion_rawleadpool DROP COLUMN IF EXISTS lead_id;",
                ),
            ],
            # State: keep Django's model state in sync
            state_operations=[
                migrations.AddField(
                    model_name='rawleadpool',
                    name='lead',
                    field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='bulk_upload.manualentry'),
                    preserve_default=False,
                ),
            ],
        ),
    ]
