# Generated by Django 6.0.2 on 2026-03-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('rememeber_me', models.BooleanField(default=False)),
                ('sign_in', models.BooleanField(default=False)),
                ('create_account', models.BooleanField(default=False)),
            ],
        ),
    ]
