server {
    listen 80;
    server_name 13.232.219.91;

    location /master-admin/ {
        root /var/www/html;
        index index.html;
        try_files $uri $uri/ /master-admin/index.html;
    }
}
